# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('organization', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=120)),
                ('reporter', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='main_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_reported_by', to='sync_first_app.Person'),
        ),
        migrations.AddField(
            model_name='incident',
            name='spouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_reported_about', to='sync_first_app.Person'),
        ),
    ]
